### ISSUE TITLE
task cis-xlsx-to-oscal-catalog fails to find column named `references`

### ISSUE THREAD

**Issue by degenaro** [oscal-compass/compliance-trestle#1658]
## Describe the bug
 
When the subject .xlsx file has `references` as the last column, it is not found when making the transformation to OSCAL .json

## To Reproduce

Run task with subject .xlsx file having `references` as the last column on the `Combined Profiles` sheet

## Expected behavior

The .xlsx should be processed w/o error.

## Screenshots / Logs.

```
Traceback (most recent call last):
  File "/tmp/venv.cis-benchmarks/lib/python3.9/site-packages/trestle/tasks/cis_xlsx_to_oscal_catalog.py", line 265, in execute
    return self._execute()
  File "/tmp/venv.cis-benchmarks/lib/python3.9/site-packages/trestle/tasks/cis_xlsx_to_oscal_catalog.py", line 352, in _execute
    self._process_ocp(xlsx_helper, catalog_helper)
  File "/tmp/venv.cis-benchmarks/lib/python3.9/site-packages/trestle/tasks/cis_xlsx_to_oscal_catalog.py", line 400, in _process_ocp
    self._add_links(xlsx_helper, catalog_helper, links, row, 'references')
  File "/tmp/venv.cis-benchmarks/lib/python3.9/site-packages/trestle/tasks/cis_xlsx_to_oscal_catalog.py", line 317, in _add_links
    value = xlsx_helper.get(row, key)
  File "/tmp/venv.cis-benchmarks/lib/python3.9/site-packages/trestle/tasks/cis_xlsx_to_oscal_catalog.py", line 100, in get
    col = self._col_name_to_number[cname]
KeyError: 'references'

trestle.core.commands.task:94 ERROR: Error while executing Trestle task: Task cis-xlsx-to-oscal-catalog reported a TaskOutcome.FAILURE
```

## Environment

- OS: Red Hat 8.9
- Python version: 3.9.9
- Installed packages: compliance-trestle

**Comment by degenaro** [comment]
Closed by #1657
